In [1]:
a=10
a

10

In [3]:
a=10
b=20
a
b

20

In [5]:
a=[22,33,44,55]
a

[22, 33, 44, 55]

In [7]:
import numpy as np
score=np.array(a)
score

array([22, 33, 44, 55])

In [9]:
d=np.mean(score)
d

38.5

In [11]:
print(np.max(score))

55


In [12]:
print(np.min(score))

22


In [15]:
f=np.zeros([3,4])
f

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
f=np.ones([5,5])
f

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
g=np.random.rand(5,4)

g

array([[0.18552305, 0.805473  , 0.93219516, 0.51530595],
       [0.57965   , 0.74100981, 0.21901827, 0.42394648],
       [0.3428551 , 0.23083147, 0.98456361, 0.39474193],
       [0.73712521, 0.60073998, 0.08455716, 0.11440662],
       [0.27491896, 0.04932769, 0.90117499, 0.43947481]])

In [22]:
a=np.array([11,22,33,4,5,6,7,8,9,2,4,6,1,22,3,4])
d=np.reshape(a,(2,8))
d

array([[11, 22, 33,  4,  5,  6,  7,  8],
       [ 9,  2,  4,  6,  1, 22,  3,  4]])

In [23]:
b=np.arange(15).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
c=np.array([11,22,33,4,5,6,7,8,9,2,4,6,1,22,3,4])
d=c[3:6]
d

array([4, 5, 6])

In [25]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a+b

array([5, 7, 9])

In [26]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a-b

array([-3, -3, -3])

In [27]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a*b

array([ 4, 10, 18])

In [48]:
a = np.array([[1,2,3],[6,7,8]])
b = np.array([[4,5],
              [8,4],
              [6,5]])
c=np.dot(a,b)
c

array([[ 38,  28],
       [128,  98]])

In [49]:
mat = np.array([[1,2,3],[4,5,6]])
print(mat.T)

[[1 4]
 [2 5]
 [3 6]]


In [50]:
arr = np.array([5,2,8,1,9])
print(np.sort(arr))

[1 2 5 8 9]


In [51]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate((a,b)))

[1 2 3 4 5 6]


In [53]:
arr = np.array([1,2,2,3,4,4,5])
d=np.unique(arr)
d

array([1, 2, 3, 4, 5])

In [54]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [61]:
arr = np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]
